In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
import yfinance as yf

df = yf.download("^NSEI", start="2010-01-01")
df.reset_index(inplace=True)

[*********************100%***********************]  1 of 1 completed

In [5]:
import pandas as pd

raw_path = "../data/raw/nifty_50_yfinance_raw.csv"

df = pd.read_csv(
    raw_path,
    skiprows=2,
    parse_dates=['Date']
)

df.head()

        Date   Unnamed: 1   Unnamed: 2   Unnamed: 3   Unnamed: 4  Unnamed: 5
0 2015-01-02  8395.450195  8410.599609  8288.700195  8288.700195      101900
1 2015-01-05  8378.400391  8445.599609  8363.900391  8407.950195      118200
2 2015-01-06  8127.350098  8327.849609  8111.350098  8325.299805      172800
3 2015-01-07  8102.100098  8151.200195  8065.450195  8118.649902      164100
4 2015-01-08  8234.599609  8243.500000  8167.299805  8191.399902      143800

In [6]:
df.columns = [
    "Date",
    "Close",
    "High",
    "Low",
    "Open",
    "Volume"
]

df.head()

        Date        Close         High          Low         Open  Volume
0 2015-01-02  8395.450195  8410.599609  8288.700195  8288.700195  101900
1 2015-01-05  8378.400391  8445.599609  8363.900391  8407.950195  118200
2 2015-01-06  8127.350098  8327.849609  8111.350098  8325.299805  172800
3 2015-01-07  8102.100098  8151.200195  8065.450195  8118.649902  164100
4 2015-01-08  8234.599609  8243.500000  8167.299805  8191.399902  143800

In [7]:
df = df.sort_values("Date")
df = df.set_index("Date")

df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2734 entries, 2015-01-02 to 2026-02-09
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   2734 non-null   float64
 1   High    2734 non-null   float64
 2   Low     2734 non-null   float64
 3   Open    2734 non-null   float64
 4   Volume  2734 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 128.2 KB

In [8]:
df = df[["Open", "High", "Low", "Close", "Volume"]]
df.head()

                   Open         High          Low        Close  Volume
Date
2015-01-02  8288.700195  8410.599609  8288.700195  8395.450195  101900
2015-01-05  8407.950195  8445.599609  8363.900391  8378.400391  118200
2015-01-06  8325.299805  8327.849609  8111.350098  8127.350098  172800
2015-01-07  8118.649902  8151.200195  8065.450195  8102.100098  164100
2015-01-08  8191.399902  8243.500000  8167.299805  8234.599609  143800

In [9]:
df.isna().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [10]:
import os

clean_dir = "../data/raw/clean"
os.makedirs(clean_dir, exist_ok=True)

In [11]:
clean_path = "../data/raw/clean/nifty_50_clean.csv"
df.to_csv(clean_path)

print("Clean NIFTY 50 data saved successfully.")

Clean NIFTY 50 data saved successfully.